import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it, vi } from 'vitest'
import RootLayout, { metadata } from '../layout'

vi.mock('next/font/google', () => ({
  Geist: () => ({ variable: 'geist-sans' }),
  Geist_Mono: () => ({ variable: 'geist-mono' }),
}))

describe('RootLayout', () => {
  it('sets the expected metadata defaults', () => {
    expect(metadata.title).toBe('Create Next App')
    expect(metadata.description).toBe('Generated by create next app')
  })

  it('renders children inside html/body shell', () => {
    const markup = renderToStaticMarkup(
      <RootLayout>
        <main>child content</main>
      </RootLayout>,
    )

    expect(markup).toContain('lang="en"')
    expect(markup).toContain('child content')
    expect(markup).toContain('geist-sans')
    expect(markup).toContain('geist-mono')
  })
})
